services:
  - type: web
    name: dev-fun
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: CI
        value: "false"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 